// <auto-generated />
using System;
using AulaIA.Api.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AulaIA.Api.Shared.Persistence.Migrations
{
    [DbContext(typeof(AulaIADbContext))]
    [Migration("20260607212516_SeedEzequielPlaneamientoDemo")]
    partial class SeedEzequielPlaneamientoDemo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CondicionEspecial")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("condicion_especial");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByAuth0Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_auth0_sub");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("diagnostico");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("EstrategiasEvaluacion")
                        .HasColumnType("text")
                        .HasColumnName("estrategias_evaluacion");

                    b.Property<string>("EstrategiasMediacion")
                        .HasColumnType("text")
                        .HasColumnName("estrategias_mediacion");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<string>("PropuestaGenerada")
                        .HasColumnType("text")
                        .HasColumnName("propuesta_generada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId", "GroupId")
                        .IsUnique();

                    b.ToTable("accommodations", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Present")
                        .HasColumnName("status")
                        .HasComment("Present | Absent | Late | Justified");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Date")
                        .HasDatabaseName("ix_attendance_group_date");

                    b.HasIndex("StudentId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_student_date");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByAuth0Sub")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_auth0_sub");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer")
                        .HasColumnName("school_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Date");

                    b.HasIndex("SchoolYear", "GroupId");

                    b.ToTable("calendar_events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff000002-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            Date = new DateOnly(2026, 2, 23),
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            SchoolYear = 2026,
                            Title = "Acto cívico institucional",
                            Type = "Civic"
                        },
                        new
                        {
                            Id = new Guid("ff000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            Date = new DateOnly(2026, 3, 16),
                            EndDate = new DateOnly(2026, 3, 20),
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            SchoolYear = 2026,
                            Title = "Semana de exámenes I Trimestre",
                            Type = "Exam"
                        },
                        new
                        {
                            Id = new Guid("ff000002-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            Date = new DateOnly(2026, 3, 27),
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            SchoolYear = 2026,
                            Title = "Consejo de profesores",
                            Type = "TeacherMeeting"
                        },
                        new
                        {
                            Id = new Guid("ff000002-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            Date = new DateOnly(2026, 4, 13),
                            EndDate = new DateOnly(2026, 4, 17),
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            SchoolYear = 2026,
                            Title = "FEA institucional",
                            Type = "SportWeek"
                        },
                        new
                        {
                            Id = new Guid("ff000002-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            Date = new DateOnly(2026, 4, 24),
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            SchoolYear = 2026,
                            Title = "Capacitación institucional",
                            Type = "Institutional"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseAmountCrc")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_amount_crc");

                    b.Property<decimal>("CommissionAmountCrc")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("commission_amount_crc");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("GrossRevenueCrc")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("gross_revenue_crc");

                    b.Property<decimal>("InfraCostCrc")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("infra_cost_crc");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("ReferralCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_code_id");

                    b.Property<Guid>("ReferredUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("referred_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId");

                    b.HasIndex("ReferralCodeId", "ReferredUserId", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_commissions_referral_user_month");

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfSourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("curriculum_extractions", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastEtag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastModifiedMep")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MepUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Asignatura", "Ciclo")
                        .IsUnique();

                    b.ToTable("curriculum_sources", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AprendizajesEsperados")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string>("ContenidoActitudinal")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("ContenidoConceptual")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("ContenidoProcedimental")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("EstrategiasSugeridas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("IndicadoresEvaluacion")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("Trimestre")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UnidadNumero")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId");

                    b.HasIndex("Asignatura", "Nivel", "Trimestre", "UnidadNumero")
                        .IsUnique();

                    b.ToTable("curriculum_units", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.EvaluationActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(100m)
                        .HasColumnName("max_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage")
                        .HasComment("Porcentaje que representa dentro del período, ej. 20.00");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type")
                        .HasComment("Ej: 'Prueba Escrita', 'Trabajo Cotidiano', 'Proyecto', 'Portafolio'");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_eval_activities_group_id");

                    b.ToTable("evaluation_activities", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal>("UsdToCrc")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("usd_to_crc");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_rates_date");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score")
                        .HasComment("Nota obtenida, ej. 87.50");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_grades_group_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_grades_student_id");

                    b.HasIndex("ActivityId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_grades_activity_student");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level")
                        .HasComment("Año/nivel escolar, ej. '7° Año'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PctCotidiano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(20m)
                        .HasColumnName("pct_cotidiano")
                        .HasComment("% Trabajo Cotidiano (MEP default 20)");

                    b.Property<decimal>("PctExtraclase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(20m)
                        .HasColumnName("pct_extraclase")
                        .HasComment("% Trabajo Extraclase (MEP default 20)");

                    b.Property<decimal>("PctOtros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(15m)
                        .HasColumnName("pct_otros")
                        .HasComment("% Otros (MEP default 15)");

                    b.Property<decimal>("PctPruebas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(45m)
                        .HasColumnName("pct_pruebas")
                        .HasComment("% Pruebas y Exámenes (MEP default 45)");

                    b.Property<int>("SchoolYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2026)
                        .HasColumnName("school_year");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject")
                        .HasComment("Materia, ej. 'Matemáticas'");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherSub")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("teacher_sub")
                        .HasComment("Auth0 sub del docente — usado por PowerSync Sync Rules para filtrar sin casts de UUID.");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_groups_institution_id");

                    b.HasIndex("TeacherId", "SchoolYear")
                        .HasDatabaseName("ix_groups_teacher_year");

                    b.ToTable("groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc000002-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstitutionId = new Guid("aa000001-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Level = "7° Año",
                            Name = "7-1 Artes Plásticas",
                            PctCotidiano = 20m,
                            PctExtraclase = 20m,
                            PctOtros = 15m,
                            PctPruebas = 45m,
                            SchoolYear = 2026,
                            Subject = "Artes Plásticas",
                            TeacherId = new Guid("bb000001-0000-0000-0000-000000000001"),
                            TeacherSub = "auth0|69fae47c268da9d7e46c6d4b"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CircuitCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("circuit_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_institutions_name");

                    b.ToTable("institutions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000001"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Aserrí",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000002"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Aserrí",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000003"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Nocturno de Aserrí",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000004"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo San Gabriel",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000005"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Desamparados",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000006"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Desamparados",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000007"),
                            CircuitCode = "03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo Ing. Manuel Benavides",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000008"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Costa Rica",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000009"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio de Señoritas",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000010"),
                            CircuitCode = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo Julio Fonseca",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000011"),
                            CircuitCode = "03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo José Joaquín Vargas Calvo",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000012"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Guadalupe",
                            RegionCode = "SJN"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000013"),
                            CircuitCode = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Moravia",
                            RegionCode = "SJN"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000014"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Heredia",
                            RegionCode = "HER"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000015"),
                            CircuitCode = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo Daniel Oduber Quirós",
                            RegionCode = "HER"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000016"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Cartago",
                            RegionCode = "CAR"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000017"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Cartago",
                            RegionCode = "CAR"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000018"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Alajuela",
                            RegionCode = "ALA"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000019"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional Jesús Ocaña Rojas",
                            RegionCode = "ALA"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000020"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Escazú",
                            RegionCode = "SJO"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer")
                        .HasColumnName("anio_lectivo");

                    b.Property<string>("ArchivoBlobUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo_blob_url");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asignatura");

                    b.Property<string>("ContenidoGenerado")
                        .HasColumnType("text")
                        .HasColumnName("contenido_generado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("LeccionesPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("lecciones_por_semana");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TeacherSub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("teacher_sub");

                    b.Property<int>("Trimestre")
                        .HasColumnType("integer")
                        .HasColumnName("trimestre");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSub");

                    b.HasIndex("GroupId", "Trimestre", "AnioLectivo");

                    b.ToTable("lesson_plans", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.LlmAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("component");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text")
                        .HasColumnName("context_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("intent");

                    b.Property<bool>("IsError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_error");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_llm_audit_entries_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_llm_audit_entries_created_at");

                    b.HasIndex("IsError")
                        .HasDatabaseName("ix_llm_audit_entries_is_error");

                    b.ToTable("llm_audit_entries", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.PaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("admin_note");

                    b.Property<decimal>("AmountCrc")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_crc");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("exchange_rate_used");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference_code");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedByAuth0Sub")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reviewed_by_auth0_sub");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VoucherBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("voucher_blob_path");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_requests_reference_code");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payment_requests_user_id");

                    b.ToTable("payment_requests", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.ReferralCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_referral_codes_code");

                    b.HasIndex("UserId");

                    b.ToTable("referral_codes", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("qr_code")
                        .HasComment("UUID sin guiones — payload del código QR para asistencia");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_code")
                        .HasComment("Número de expediente MEP");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_students_group_id");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasDatabaseName("ix_students_qr_code");

                    b.HasIndex("StudentCode", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_code_group");

                    b.ToTable("students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Valeria Arias Montero",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000001",
                            StudentCode = "AP7-2026-001"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Sebastián Barrantes Solís",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000002",
                            StudentCode = "AP7-2026-002"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "María José Brenes Castro",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000003",
                            StudentCode = "AP7-2026-003"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Diego Calderón Vargas",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000004",
                            StudentCode = "AP7-2026-004"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Camila Campos Rojas",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000005",
                            StudentCode = "AP7-2026-005"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Andrés Cordero Jiménez",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000006",
                            StudentCode = "AP7-2026-006"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Sofía Delgado Mora",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000007",
                            StudentCode = "AP7-2026-007"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Daniela Díaz Hernández",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000008",
                            StudentCode = "AP7-2026-008"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Samuel Fernández Chaves",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000009",
                            StudentCode = "AP7-2026-009"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Lucía Flores Quesada",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000010",
                            StudentCode = "AP7-2026-010"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Mateo García López",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000011",
                            StudentCode = "AP7-2026-011"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Isabella Gómez Arce",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000012",
                            StudentCode = "AP7-2026-012"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Emiliano Gutiérrez Salazar",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000013",
                            StudentCode = "AP7-2026-013"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Natalia Herrera Ulate",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000014",
                            StudentCode = "AP7-2026-014"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Gabriel Jiménez Rodríguez",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000015",
                            StudentCode = "AP7-2026-015"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Paula León Sánchez",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000016",
                            StudentCode = "AP7-2026-016"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Julián López Núñez",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000017",
                            StudentCode = "AP7-2026-017"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Mariana Martínez Vega",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000018",
                            StudentCode = "AP7-2026-018"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Esteban Méndez Castro",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000019",
                            StudentCode = "AP7-2026-019"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Ana Lucía Molina Rojas",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000020",
                            StudentCode = "AP7-2026-020"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "José Pablo Mora Alfaro",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000021",
                            StudentCode = "AP7-2026-021"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Daniel Navarro Céspedes",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000022",
                            StudentCode = "AP7-2026-022"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Fernanda Núñez Chacón",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000023",
                            StudentCode = "AP7-2026-023"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Adrián Pacheco Soto",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000024",
                            StudentCode = "AP7-2026-024"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nicole Pérez Bonilla",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000025",
                            StudentCode = "AP7-2026-025"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Luis Diego Quesada Ramírez",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000026",
                            StudentCode = "AP7-2026-026"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Laura Ramírez Fallas",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000027",
                            StudentCode = "AP7-2026-027"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Fabián Rojas Hidalgo",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000028",
                            StudentCode = "AP7-2026-028"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Daniela Salazar Picado",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000029",
                            StudentCode = "AP7-2026-029"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Christopher Sánchez Vargas",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000030",
                            StudentCode = "AP7-2026-030"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Michelle Segura Campos",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000031",
                            StudentCode = "AP7-2026-031"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Kevin Solano Aguilar",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000032",
                            StudentCode = "AP7-2026-032"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Ariana Soto Morales",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000033",
                            StudentCode = "AP7-2026-033"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Brandon Torres Rivas",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000034",
                            StudentCode = "AP7-2026-034"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Melissa Ureña Castro",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000035",
                            StudentCode = "AP7-2026-035"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Anthony Valverde Mora",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000036",
                            StudentCode = "AP7-2026-036"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Karla Vargas Esquivel",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000037",
                            StudentCode = "AP7-2026-037"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Jeremy Vega Delgado",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000038",
                            StudentCode = "AP7-2026-038"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000039"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Tatiana Villalobos Cordero",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000039",
                            StudentCode = "AP7-2026-039"
                        },
                        new
                        {
                            Id = new Guid("dd000002-0000-0000-0000-000000000040"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Santiago Zamora Ruiz",
                            GroupId = new Guid("cc000002-0000-0000-0000-000000000001"),
                            IsActive = true,
                            QrCode = "dd000002000000000000000000000040",
                            StudentCode = "AP7-2026-040"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trial");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth0_sub");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<string>("ReferredByCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("referred_by_code");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Teacher")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0_sub");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_users_institution_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb000001-0000-0000-0000-000000000001"),
                            Auth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ezekiell1988@hotmail.com",
                            FullName = "Ezequiel Baltodano",
                            InstitutionId = new Guid("aa000001-0000-0000-0000-000000000001"),
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Accommodation", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AulaIA.Api.Shared.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_group");

                    b.HasOne("AulaIA.Api.Shared.Domain.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_student");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CalendarEvent", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Commission", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.ReferralCode", "ReferralCode")
                        .WithMany("Commissions")
                        .HasForeignKey("ReferralCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AulaIA.Api.Shared.Domain.User", "ReferredUser")
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferralCode");

                    b.Navigation("ReferredUser");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumUnit", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.CurriculumExtraction", "Extraction")
                        .WithMany("Units")
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extraction");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.EvaluationActivity", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany("EvaluationActivities")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eval_activities_group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Grade", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.EvaluationActivity", "Activity")
                        .WithMany("Grades")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_activity");

                    b.HasOne("AulaIA.Api.Shared.Domain.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_student");

                    b.Navigation("Activity");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Group", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Institution", "Institution")
                        .WithMany("Groups")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_institution");

                    b.HasOne("AulaIA.Api.Shared.Domain.User", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_teacher");

                    b.Navigation("Institution");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.LessonPlan", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.PaymentRequest", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Subscription", null)
                        .WithMany("PaymentRequests")
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("AulaIA.Api.Shared.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.ReferralCode", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Student", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Subscription", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("AulaIA.Api.Shared.Domain.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.User", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_institution");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumExtraction", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.EvaluationActivity", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Group", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EvaluationActivities");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Institution", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.ReferralCode", b =>
                {
                    b.Navigation("Commissions");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Subscription", b =>
                {
                    b.Navigation("PaymentRequests");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.User", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
