// <auto-generated />
using System;
using AulaIA.Api.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AulaIA.Api.Shared.Persistence.Migrations
{
    [DbContext(typeof(AulaIADbContext))]
    [Migration("20260507052325_AddGroupWeighting")]
    partial class AddGroupWeighting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Present")
                        .HasColumnName("status")
                        .HasComment("Present | Absent | Late | Justified");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Date")
                        .HasDatabaseName("ix_attendance_group_date");

                    b.HasIndex("StudentId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_student_date");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfSourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("curriculum_extractions", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AprendizajesEsperados")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string>("ContenidoActitudinal")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("ContenidoConceptual")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("ContenidoProcedimental")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("EstrategiasSugeridas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("IndicadoresEvaluacion")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("Trimestre")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UnidadNumero")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId");

                    b.HasIndex("Asignatura", "Nivel", "Trimestre", "UnidadNumero")
                        .IsUnique();

                    b.ToTable("curriculum_units", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.EvaluationActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(100m)
                        .HasColumnName("max_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage")
                        .HasComment("Porcentaje que representa dentro del período, ej. 20.00");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type")
                        .HasComment("Ej: 'Prueba Escrita', 'Trabajo Cotidiano', 'Proyecto', 'Portafolio'");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_eval_activities_group_id");

                    b.ToTable("evaluation_activities", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score")
                        .HasComment("Nota obtenida, ej. 87.50");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_grades_group_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_grades_student_id");

                    b.HasIndex("ActivityId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_grades_activity_student");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level")
                        .HasComment("Año/nivel escolar, ej. '7° Año'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PctCotidiano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(20m)
                        .HasColumnName("pct_cotidiano")
                        .HasComment("% Trabajo Cotidiano (MEP default 20)");

                    b.Property<decimal>("PctExtraclase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(20m)
                        .HasColumnName("pct_extraclase")
                        .HasComment("% Trabajo Extraclase (MEP default 20)");

                    b.Property<decimal>("PctOtros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(15m)
                        .HasColumnName("pct_otros")
                        .HasComment("% Otros (MEP default 15)");

                    b.Property<decimal>("PctPruebas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(45m)
                        .HasColumnName("pct_pruebas")
                        .HasComment("% Pruebas y Exámenes (MEP default 45)");

                    b.Property<int>("SchoolYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2026)
                        .HasColumnName("school_year");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject")
                        .HasComment("Materia, ej. 'Matemáticas'");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherSub")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("teacher_sub")
                        .HasComment("Auth0 sub del docente — usado por PowerSync Sync Rules para filtrar sin casts de UUID.");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_groups_institution_id");

                    b.HasIndex("TeacherId", "SchoolYear")
                        .HasDatabaseName("ix_groups_teacher_year");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CircuitCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("circuit_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_institutions_name");

                    b.ToTable("institutions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000001"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Aserrí",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000002"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Aserrí",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000003"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Nocturno de Aserrí",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000004"),
                            CircuitCode = "06",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo San Gabriel",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000005"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Desamparados",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000006"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Desamparados",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000007"),
                            CircuitCode = "03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo Ing. Manuel Benavides",
                            RegionCode = "DES"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000008"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Costa Rica",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000009"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio de Señoritas",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000010"),
                            CircuitCode = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo Julio Fonseca",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000011"),
                            CircuitCode = "03",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo José Joaquín Vargas Calvo",
                            RegionCode = "SJC"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000012"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Guadalupe",
                            RegionCode = "SJN"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000013"),
                            CircuitCode = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Moravia",
                            RegionCode = "SJN"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000014"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Heredia",
                            RegionCode = "HER"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000015"),
                            CircuitCode = "02",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo Daniel Oduber Quirós",
                            RegionCode = "HER"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000016"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Cartago",
                            RegionCode = "CAR"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000017"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional de Cartago",
                            RegionCode = "CAR"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000018"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Alajuela",
                            RegionCode = "ALA"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000019"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colegio Técnico Profesional Jesús Ocaña Rojas",
                            RegionCode = "ALA"
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000020"),
                            CircuitCode = "01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liceo de Escazú",
                            RegionCode = "SJO"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer")
                        .HasColumnName("anio_lectivo");

                    b.Property<string>("ArchivoBlobUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo_blob_url");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asignatura");

                    b.Property<string>("ContenidoGenerado")
                        .HasColumnType("text")
                        .HasColumnName("contenido_generado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("LeccionesPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("lecciones_por_semana");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TeacherSub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("teacher_sub");

                    b.Property<int>("Trimestre")
                        .HasColumnType("integer")
                        .HasColumnName("trimestre");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSub");

                    b.HasIndex("GroupId", "Trimestre", "AnioLectivo");

                    b.ToTable("lesson_plans", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("qr_code")
                        .HasComment("UUID sin guiones — payload del código QR para asistencia");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_code")
                        .HasComment("Número de expediente MEP");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_students_group_id");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasDatabaseName("ix_students_qr_code");

                    b.HasIndex("StudentCode", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_code_group");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth0_sub");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Teacher")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0_sub");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_users_institution_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb000001-0000-0000-0000-000000000001"),
                            Auth0Sub = "auth0|69fae47c268da9d7e46c6d4b",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ezekiell1988@hotmail.com",
                            FullName = "Ezequiel Baltodano",
                            InstitutionId = new Guid("aa000001-0000-0000-0000-000000000001"),
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bb000001-0000-0000-0000-000000000002"),
                            Auth0Sub = "auth0|PLACEHOLDER_ADRIANA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ezekiell1988@gmail.com",
                            FullName = "Adriana Guido",
                            InstitutionId = new Guid("aa000001-0000-0000-0000-000000000001"),
                            Role = "Teacher"
                        });
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_group");

                    b.HasOne("AulaIA.Api.Shared.Domain.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_student");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumUnit", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.CurriculumExtraction", "Extraction")
                        .WithMany("Units")
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extraction");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.EvaluationActivity", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany("EvaluationActivities")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eval_activities_group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Grade", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.EvaluationActivity", "Activity")
                        .WithMany("Grades")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_activity");

                    b.HasOne("AulaIA.Api.Shared.Domain.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_student");

                    b.Navigation("Activity");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Group", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Institution", "Institution")
                        .WithMany("Groups")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_institution");

                    b.HasOne("AulaIA.Api.Shared.Domain.User", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_teacher");

                    b.Navigation("Institution");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.LessonPlan", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Student", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.User", b =>
                {
                    b.HasOne("AulaIA.Api.Shared.Domain.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_institution");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.CurriculumExtraction", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.EvaluationActivity", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Group", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EvaluationActivities");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Institution", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("AulaIA.Api.Shared.Domain.User", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
